### PR TITLE
feat: auto focus password input

### PR DESCRIPTION
**Pull request by FradSer**
Tested in iOS and web. Plz help me to test in Android deveices.😘

### CODE REVIEW

**Comment by ByteZhang1024** [comment]
Whether it meets expectations.

https://user-images.githubusercontent.com/92281880/166134221-424eb0a8-5209-4162-8d08-7aba0feeaa51.mp4

**Comment by FradSer** [comment]
@ByteZhang1024 LGTM。五一快乐。

**Comment by revan-zhang** [comment]
Thanks, but duplicated with https://github.com/OneKeyHQ/app-monorepo/pull/634, will close this one after #634 has been merged.

Also please take a look at lint and type issues by running `yarn lint` at local.

**Comment by kwoktung** [comment]
duplicated

https://github.com/OneKeyHQ/app-monorepo/pull/634

**Comment by revan-zhang** [comment]
https://github.com/OneKeyHQ/app-monorepo/pull/634 has been merged

**Pull request closed without merging**
