### PR TITLE
chore: remove expo-yarn-workspace

### PR DESCRIPTION
**Pull request by sunnylqm**
remove expo-yarn-workspace as suggested by expo https://docs.expo.dev/guides/monorepos/#remove-expo-yarn-workspaces

### CODE REVIEW

**Comment by QuincySx** [comment]
@sunnylqm 这个 PR 为什么关闭了。

**Comment by sunnylqm** [comment]
在后续的expo48 pr中延续了

**Comment by ByteZhang1024** [comment]
然后为了修复 hot reload 又改回来了 https://github.com/OneKeyHQ/app-monorepo/pull/3025

**Comment by sunnylqm** [comment]
也没有改回来，只是借用了里面的一些处理逻辑，https://github.com/expo/expo/blob/main/packages/expo-yarn-workspaces/webpack.js#L23-L49

**Pull request closed without merging**
